all : mutex deadlock parallel_factorial

mutex : mutex.c
	gcc -o mutex mutex.c
deadlock : deadlock.c
	gcc -o deadlock deadlock.c
parallel_factorial : parallel_factorial.c
	gcc -o parallel_factorial parallel_factorial.c
clean : 
	rm mutex deadlock parallel_factorial
