CC=gcc

all : tcpclient tcpserver udpclient udpserver

tcpclient : 
	$(CC) tcpclient.c -o tcpclient

tcpserver :
	$(CC) tcpserver.c -o tcpserver

udpclient :
	$(CC) udpclient.c -o udpclient

udpserver :
	$(CC) udpserver.c -o udpserver

clean : 
	rm tcpclient tcpserver udpclient udpserver