CC=gcc
CFLAGS=-I.

sequential_min_max : utils.o find_min_max.o utils.h find_min_max.h
	$(CC) -o sequential_min_max find_min_max.o utils.o sequential_min_max.c $(CFLAGS)

parallel_min_max : utils.o find_min_max.o utils.h find_min_max.h
	$(CC) -o parallel_min_max utils.o find_min_max.o parallel_min_max.c $(CFLAGS)

utils.o : utils.h
	$(CC) -o utils.o -c utils.c $(CFLAGS)

find_min_max.o : utils.h find_min_max.h
	$(CC) -o find_min_max.o -c find_min_max.c $(CFLAGS) 
execute: execute_seq.c
	$(CC) -o execute execute_seq.c
clean : 
	rm utils.o find_min_max.o sequential_min_max parallel_min_max execute
all : execute_seq.c utils.c find_min_max.c parallel_min_max.c sequential_min_max.c 
	$(CC) -o utils.o -c utils.c $(CFLAGS)
	$(CC) -o find_min_max.o -c find_min_max.c $(CFLAGS)
	$(CC) -o sequential_min_max utils.o find_min_max.o sequential_min_max.c
	$(CC) -o parallel_min_max utils.o find_min_max.o parallel_min_max.c
	$(CC) -o execute execute_seq.c